package com.example.treinospring.servicos.exceptions;

public class RecursoNaoEncontradoException extends RuntimeException{

    public RecursoNaoEncontradoException(Object id){
        super("Recurso n√£o encontrado. Id : " + id);
    }
}
